export interface Paciente {
  id_paciente: number;
  id_persona: number;
  id_sucursal: number;
  rut: string;
  nombres: string;
  apellidos: string;
  fecha_nacimiento: string;
  genero: string;
  telefono: string;
  email: string;
  direccion: string;
  nacionalidad: string | null;
  prevision: string;
  estado_civil: string | null;
  numero_hijos: number | null;
  escolaridad: string | null;
  profesion_ocupacion: string | null;
  comuna: string | null;
  empresa_nombre: string | null;
  apoderado_nombre: string | null;
  apoderado_parentesco: string | null;
  apoderado_edad: number | null;
  apoderado_direccion: string | null;
  apoderado_telefono: string | null;
  contacto_emergencia_nombre: string;
  contacto_emergencia_parentesco: string;
  contacto_emergencia_telefono: string;
  contacto_emergencia_email: string;
  contacto2_nombre: string | null;
  contacto2_parentesco: string | null;
  contacto2_telefono: string | null;
  contacto2_email: string | null;
  activo: boolean;
  nombre_sucursal?: string;
}

export interface PacienteForm {
  rut: string;
  nombres: string;
  apellidos: string;
  fecha_nacimiento: string;
  genero: string;
  telefono: string;
  email: string;
  direccion: string;
  nacionalidad: string;
  id_sucursal: number;
  prevision: string;
  estado_civil?: string;
  numero_hijos?: number | null;
  escolaridad?: string;
  profesion_ocupacion?: string;
  comuna?: string;
  empresa_nombre?: string;
  apoderado_nombre?: string;
  apoderado_parentesco?: string;
  apoderado_edad?: number | null;
  apoderado_direccion?: string;
  apoderado_telefono?: string;
  contacto_emergencia_nombre: string;
  contacto_emergencia_parentesco: string;
  contacto_emergencia_telefono: string;
  contacto_emergencia_email: string;
  contacto2_nombre: string;
  contacto2_parentesco: string;
  contacto2_telefono: string;
  contacto2_email: string;
  activo?: boolean;
}
