const NACIONALIDADES = [
  'Afgana', 'Albanesa', 'Alemana', 'Andorrana', 'Angoleña', 'Antigua y Barbudana',
  'Argelina', 'Argentina', 'Armenia', 'Australiana', 'Austriaca', 'Azerbaiyana',
  'Bahameña', 'Bangladesí', 'Barbadense', 'Belga', 'Beliceña', 'Beninesa',
  'Bielorrusa', 'Boliviana', 'Bosnia', 'Botsuanesa', 'Brasileña', 'Británica',
  'Bruneyana', 'Búlgara', 'Burkinesa', 'Burundesa', 'Butanesa', 'Caboverdiana',
  'Camboyana', 'Camerunesa', 'Canadiense', 'Catarí', 'Chadiana', 'Chilena',
  'China', 'Chipriota', 'Colombiana', 'Comorense', 'Congoleña', 'Costarricense',
  'Croata', 'Cubana', 'Danesa', 'Dominicana', 'Ecuatoguineana', 'Ecuatoriana',
  'Egipcia', 'Emiratense', 'Eritrea', 'Eslovaca', 'Eslovena', 'Española',
  'Estadounidense', 'Estonia', 'Etíope', 'Fiyiana', 'Filipina', 'Finlandesa',
  'Francesa', 'Gabonesa', 'Gambiana', 'Georgiana', 'Ghanesa', 'Granadina',
  'Griega', 'Guatemalteca', 'Guineana', 'Guineana-bisauense', 'Guyanesa',
  'Haitiana', 'Hondureña', 'Húngara', 'India', 'Indonesia', 'Iraní', 'Iraquí',
  'Irlandesa', 'Islandesa', 'Israelí', 'Italiana', 'Jamaicana', 'Japonesa',
  'Jordana', 'Kazaja', 'Keniana', 'Kirguís', 'Kiribatiana', 'Kuwaití',
  'Laosiana', 'Lesotense', 'Letona', 'Libanesa', 'Liberiana', 'Libia',
  'Liechtensteiniana', 'Lituana', 'Luxemburguesa', 'Malasia', 'Maldiva',
  'Malgache', 'Maliana', 'Maltesa', 'Marfileña', 'Marroquí', 'Mauriciana',
  'Mauritana', 'Mexicana', 'Micronesia', 'Moldava', 'Monegasca', 'Mongola',
  'Montenegrina', 'Mozambiqueña', 'Namibia', 'Nauruana', 'Nepalesa',
  'Neozelandesa', 'Nicaragüense', 'Nigeriana', 'Nigerina', 'Noruega', 'Omaní',
  'Pakistaní', 'Palauana', 'Palestina', 'Panameña', 'Papú', 'Paraguaya',
  'Peruana', 'Polaca', 'Portuguesa', 'Ruandesa', 'Rumana', 'Rusa', 'Samoana',
  'San Cristobaleña', 'Sanmarinense', 'Santa Lucense', 'Santo Tomé y Principense',
  'Saudí', 'Senegalesa', 'Serbia', 'Seychellense', 'Sierraleonesa',
  'Singapurense', 'Siria', 'Somalí', 'Sri Lankesa', 'Sudafricana', 'Sudanesa',
  'Sudanesa del Sur', 'Sueca', 'Suiza', 'Surinamesa', 'Suazilandesa',
  'Tailandesa', 'Tanzana', 'Tayika', 'Timorense', 'Togolesa', 'Tongana',
  'Trinitense', 'Tunecina', 'Turca', 'Turcomana', 'Tuvaluana', 'Ugandesa',
  'Ucraniana', 'Uruguaya', 'Uzbeka', 'Vanuatense', 'Vaticana', 'Venezolana',
  'Vietnamita', 'Yemení', 'Yibutiana', 'Zambiana', 'Zimbabuense',
];

export const NACIONALIDAD_OPTIONS = NACIONALIDADES.map((n) => ({ value: n, label: n }));
